[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "arcdsl"
version = "0.0.1"
dependencies = ["tqdm"]
requires-python = ">=3.11"
authors = []
description = "Lovely Spam! Wonderful Spam!"
readme = "README.md"
